/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import static Proyecto.tareas.aviso;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class ERecor extends javax.swing.JFrame {
    mysql con=new mysql();
    Connection cn= (Connection) con.conexion();

    /**
     * Creates new form ERecor
     */
    public ERecor() {
        initComponents();
        setSize(649, 540);
        setLocation(400,100);
        
        comprueba.setText("si");
        
        check.setVisible(true);
        check.setContentAreaFilled(false);
        check.setBorderPainted (false);
        
        update.setVisible(true);
        update.setContentAreaFilled(false);
        update.setBorderPainted (false);
        
        jButton1.setVisible(true);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted (false);
        
        back.setContentAreaFilled(false);
        back.setBorderPainted (false);
        
        comprueba.setVisible(false);
        fecha.setVisible(false);
        
        options.setVisible(true);
        options.setContentAreaFilled(false);
        options.setBorderPainted (false);
        
        aver.setVisible(false);
        
        options2.setVisible(false);
        options2.setContentAreaFilled(false);
        options2.setBorderPainted (false);
        
        
        String dato;
        dato=(aviso.getText());
        aver.setText(""+dato);
        String descr="", ver="", fech="";
        ResultSet rs;
        Statement st;
        String sql=("SELECT * from tareas WHERE CodTarea="+dato);
        try {
            st= cn.createStatement();
            rs =st.executeQuery(sql);
            while(rs.next()){
                descr=rs.getString(2);
                fech=rs.getString(3);
                ver=rs.getString(4);
            }            
        } catch (SQLException ex) {
            Logger.getLogger(ANota.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         tarea1.setText(""+descr);
         
         if (ver.equals("SI")){
             check.setSelected(true);
         }
         
         atras.setVisible(true);
        atras.setContentAreaFilled(false);
        atras.setBorderPainted (false);
        
       menub.setVisible(true);
        menub.setContentAreaFilled(false);
        menub.setBorderPainted (false);
        
        salir.setVisible(true);
        salir.setContentAreaFilled(false);
        salir.setBorderPainted (false);
        
        transparenciaButton();

    }

    
    public void transparenciaButton (){
         jButton1.setOpaque(false);
         update.setOpaque(false);  
         back.setOpaque(false);
         check.setOpaque(false);
         options.setOpaque(false);
         options2.setOpaque(false);
         atras.setOpaque(false);
         menub.setOpaque(false);
         salir.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneledicion = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        tarea1 = new javax.swing.JTextField();
        check = new javax.swing.JCheckBox();
        update = new javax.swing.JButton();
        back = new javax.swing.JButton();
        aver = new javax.swing.JTextField();
        fecha = new javax.swing.JPanel();
        añoo = new javax.swing.JSpinner();
        mess = new javax.swing.JComboBox();
        diaa = new javax.swing.JSpinner();
        options = new javax.swing.JButton();
        options2 = new javax.swing.JButton();
        comprueba = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        atras = new javax.swing.JButton();
        menub = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paneledicion.setBackground(new java.awt.Color(255, 255, 255));
        paneledicion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        paneledicion.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar_1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        paneledicion.add(jButton1);
        jButton1.setBounds(460, 70, 50, 60);

        tarea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarea1ActionPerformed(evt);
            }
        });
        paneledicion.add(tarea1);
        tarea1.setBounds(20, 30, 560, 30);
        paneledicion.add(check);
        check.setBounds(400, 80, 30, 30);

        update.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/girar.png"))); // NOI18N
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        paneledicion.add(update);
        update.setBounds(520, 70, 60, 60);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/espalda.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        paneledicion.add(back);
        back.setBounds(0, 110, 50, 40);
        paneledicion.add(aver);
        aver.setBounds(480, 80, 6, 20);

        fecha.setBackground(new java.awt.Color(255, 255, 255));
        fecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        fecha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        añoo.setModel(new javax.swing.SpinnerNumberModel(2017, 2017, 2020, 1));
        añoo.setToolTipText("");
        fecha.add(añoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 60, 30));

        mess.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre ", "Noviembre", "Diciembre" }));
        fecha.add(mess, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 90, 30));

        diaa.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        fecha.add(diaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 30));

        paneledicion.add(fecha);
        fecha.setBounds(100, 70, 240, 70);

        options.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/opciones.png"))); // NOI18N
        options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsActionPerformed(evt);
            }
        });
        paneledicion.add(options);
        options.setBounds(0, 0, 90, 30);

        options2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/opciones.png"))); // NOI18N
        options2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                options2ActionPerformed(evt);
            }
        });
        paneledicion.add(options2);
        options2.setBounds(0, 0, 90, 30);

        comprueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compruebaActionPerformed(evt);
            }
        });
        paneledicion.add(comprueba);
        comprueba.setBounds(430, 80, 20, 20);

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel2.setText("Verificación");
        paneledicion.add(jLabel2);
        jLabel2.setBounds(380, 110, 70, 20);

        getContentPane().add(paneledicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 600, 150));

        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras2.png"))); // NOI18N
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        getContentPane().add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 60, 30));

        menub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/init.png"))); // NOI18N
        menub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubActionPerformed(evt);
            }
        });
        getContentPane().add(menub, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, -1, -1));

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 30, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BASICO MEDIDAS.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 650, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int cod=Integer.parseInt(aviso.getText());
        try{         
                    PreparedStatement pps= cn.prepareStatement("DELETE FROM tareas WHERE CodTarea="+cod);
                    pps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "TAREA BORRADA");
                    dispose();
                    new tareas().setVisible(true);
     
                } catch (SQLException ex) {
                    Logger.getLogger(ERecor.class.getName()).log(Level.SEVERE, null, ex);
                }
        new tareas().setVisible(true);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tarea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarea1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarea1ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed

        String ver, des, cod, comp;
        comp=comprueba.getText();
        cod=aviso.getText();
        if (check.isSelected()==true){
            ver="SI";
        }else{
            ver="NO";
        }
        des=tarea1.getText();
        
        if ("no".equals(comp)){
            try{         
                    PreparedStatement pps= cn.prepareStatement("UPDATE tareas SET Descripcion='"+des+"', Verificacion='"+ver+"' WHERE CodTarea="+cod);
                    pps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Datos actualizados");
                    dispose();
                    new tareas().setVisible(true);
     
                } catch (SQLException ex) {
                    Logger.getLogger(ERecor.class.getName()).log(Level.SEVERE, null, ex);
                }
        }else if ("si".equals(comp)){
            String mes, mm="ene", fechita;
            int dia, año;
            mes=(String) (mess.getSelectedItem());
            switch (mes){
                case "Enero":
                    mm="ene";
                break;
                case "Febrero":
                    mm="feb";
                break;
                case "Marzo":
                    mm="mar";
                break;
                case "Abril":
                    mm="abr";
                break;
                case "Mayo":
                    mm="may";
                break;
                case "Junio":
                    mm="jun";
                break;
                case "Julio":
                    mm="jul";
                break;
                case "Agosto":
                    mm="ago";
                break;
                case "Septiembre":
                    mm="sep";
                break;
                case "Octubre":
                    mm="oct";
                break;
                case "Noviembre":
                    mm="nov";
                break;
                case "Diciembre":
                    mm="dic";  
                break;       
}

dia=(int) diaa.getValue();
año=(int) añoo.getValue();

if ("feb".equals(mm) && dia>28){
    dia=Integer.parseInt(JOptionPane.showInputDialog("Ingrese un dia menor a 28"));
    while (dia>28){
        dia=Integer.parseInt(JOptionPane.showInputDialog("Ingrese un dia menor a 28"));  
    }
}

if (("abr".equals(mm) || "jun".equals(mm) || "sep".equals(mm) || "nov".equals(mm)) && dia>30){
    dia=Integer.parseInt(JOptionPane.showInputDialog("Ingrese un dia menor a 30"));
    while (dia>30){
        dia=Integer.parseInt(JOptionPane.showInputDialog("Ingrese un dia menor a 30"));  
    }
}
fechita=(dia+"-"+mm+"-"+año);
 
            try{         
                    PreparedStatement pps= cn.prepareStatement("UPDATE tareas SET Descripcion='"+des+"', Verificacion='"+ver+"', Fecha='"+fechita+"' WHERE CodTarea="+cod);
                    pps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Datos actualizados");
                    dispose();
                    new tareas().setVisible(true);
     
                } catch (SQLException ex) {
                    Logger.getLogger(ERecor.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
                
                
                
        
       
    }//GEN-LAST:event_updateActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

        new tareas().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void optionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsActionPerformed
comprueba.setText("si");
fecha.setVisible(true);
options.setVisible(false);
options2.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_optionsActionPerformed

    private void compruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compruebaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compruebaActionPerformed

    private void options2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_options2ActionPerformed
     comprueba.setText("no");
     fecha.setVisible(false);
     options.setVisible(true);
     options2.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_options2ActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        new tareas().setVisible(true);
        dispose();
        this.setVisible(false);
    }//GEN-LAST:event_atrasActionPerformed

    private void menubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubActionPerformed
        new Ventana().setVisible(true);
        //new tareas().setVisible(false);
        //new ERecor().setVisible(false);
        this.setVisible(false);
    }//GEN-LAST:event_menubActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ERecor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ERecor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ERecor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ERecor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ERecor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JTextField aver;
    private javax.swing.JSpinner añoo;
    private javax.swing.JButton back;
    private javax.swing.JCheckBox check;
    private javax.swing.JTextField comprueba;
    private javax.swing.JSpinner diaa;
    private javax.swing.JPanel fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton menub;
    private javax.swing.JComboBox mess;
    private javax.swing.JButton options;
    private javax.swing.JButton options2;
    private javax.swing.JPanel paneledicion;
    private javax.swing.JButton salir;
    private javax.swing.JTextField tarea1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
