
package Proyecto;

import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;


public class Repasar extends javax.swing.JFrame {

    mysql con=new mysql();
    Connection cn= (Connection) con.conexion();
    /**
     * Creates new form Repasar
     */
    public Repasar() {
        initComponents();
        transparenciaButton ();
        setLocation(400,100);
        setSize(647, 559);
        
        nott.setVisible(false);
        te.setVisible(false);
        
        seguirr.setVisible(true);
        seguirr.setContentAreaFilled(false);
        seguirr.setBorderPainted (false);
        
        repasar.setVisible(false);
        repasar.setContentAreaFilled(false);
        repasar.setBorderPainted (false);
        
        combomateria.setVisible(true);
        combotema.setVisible(false);
        
        atras.setVisible(true);
        atras.setContentAreaFilled(false);
        atras.setBorderPainted (false);
        
       menub.setVisible(true);
        menub.setContentAreaFilled(false);
        menub.setBorderPainted (false);
        
        salir.setVisible(true);
        salir.setContentAreaFilled(false);
        salir.setBorderPainted (false);
        
        
        
        Statement st;
        ResultSet rs;
        String sql, matt;
        sql="SELECT * from materia";
                 try{
                    st= cn.createStatement();
                    rs=st.executeQuery(sql);

                    while(rs.next()){
                       matt=rs.getString(2);
                       combomateria.addItem(""+matt);
                       
                    }    
                }catch (SQLException ex) {
                    Logger.getLogger(ANota.class.getName()).log(Level.SEVERE, null, ex);
                }   
    }
    
    public void transparenciaButton (){
        atras.setOpaque(false);
        menub.setOpaque(false);
        salir.setOpaque(false);
        repasar.setOpaque(false);
        seguirr.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atras = new javax.swing.JButton();
        menub = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        combomateria = new javax.swing.JComboBox();
        seguirr = new javax.swing.JButton();
        combotema = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        repasar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nott = new javax.swing.JTextField();
        te = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras2.png"))); // NOI18N
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        getContentPane().add(atras);
        atras.setBounds(100, 530, 47, 29);

        menub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/init.png"))); // NOI18N
        menub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubActionPerformed(evt);
            }
        });
        getContentPane().add(menub);
        menub.setBounds(300, 530, 53, 27);

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir);
        salir.setBounds(480, 530, 51, 27);

        combomateria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Materia" }));
        combomateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combomateriaActionPerformed(evt);
            }
        });
        getContentPane().add(combomateria);
        combomateria.setBounds(70, 110, 110, 30);

        seguirr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proximo (2).png"))); // NOI18N
        seguirr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seguirrActionPerformed(evt);
            }
        });
        getContentPane().add(seguirr);
        seguirr.setBounds(210, 90, 70, 70);

        combotema.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tema" }));
        combotema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combotemaActionPerformed(evt);
            }
        });
        getContentPane().add(combotema);
        combotema.setBounds(70, 110, 110, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/libro-abierto.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 10, 64, 64);

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REPASAR EXAMEN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 0, 350, 80);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/REPA.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 700, 80);

        repasar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proximo (3).png"))); // NOI18N
        repasar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repasarActionPerformed(evt);
            }
        });
        getContentPane().add(repasar);
        repasar.setBounds(210, 90, 80, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BASICO MEDIDAS.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -30, 650, 640);
        getContentPane().add(nott);
        nott.setBounds(480, 120, 6, 20);
        getContentPane().add(te);
        te.setBounds(510, 120, 6, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        new Ventana().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_atrasActionPerformed

    private void menubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubActionPerformed
        new Ventana().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menubActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void combomateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combomateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combomateriaActionPerformed

    private void combotemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combotemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combotemaActionPerformed

    private void seguirrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seguirrActionPerformed
        Statement st;
        ResultSet rs;
        int matt=0;
        String sql, temmm;
        String materia = (String) (combomateria.getSelectedItem());
        sql="SELECT CodMateria from materia WHERE NomMateria='"+materia+"'";
                 try{
                    st= cn.createStatement();
                    rs=st.executeQuery(sql);

                    while(rs.next()){
                       matt=rs.getInt(1);
                    }    
                }catch (SQLException ex) {
                    Logger.getLogger(ANota.class.getName()).log(Level.SEVERE, null, ex);
                }  
        sql="SELECT NomTema from tema WHERE CodMateria="+matt;
                 try{
                    st= cn.createStatement();
                    rs=st.executeQuery(sql);
                    while(rs.next()){
                        temmm=rs.getString(1);
                        
                        combotema.addItem(""+temmm);
                    }    
                }catch (SQLException ex) {
                    Logger.getLogger(ANota.class.getName()).log(Level.SEVERE, null, ex);
                }  
        combomateria.setVisible(false);
        combotema.setVisible(true);
        seguirr.setVisible(false);
        repasar.setVisible(true);

        

    }//GEN-LAST:event_seguirrActionPerformed

    private void repasarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repasarActionPerformed

        String combom=(String) (combomateria.getSelectedItem());
        String temaa= (String) (combotema.getSelectedItem());
        nott.setText(""+combom);
        te.setText(""+temaa);
        new consulta().setVisible(true);
        dispose();

    }//GEN-LAST:event_repasarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Repasar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Repasar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Repasar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Repasar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Repasar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JComboBox combomateria;
    private javax.swing.JComboBox combotema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton menub;
    public static javax.swing.JTextField nott;
    private javax.swing.JButton repasar;
    private javax.swing.JButton salir;
    public static javax.swing.JButton seguirr;
    public static javax.swing.JTextField te;
    // End of variables declaration//GEN-END:variables
}
