/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class tareas extends javax.swing.JFrame {

    
    mysql con=new mysql();
    Connection cn= (Connection) con.conexion();
    /**
     * Creates new form tareas
     */
    public tareas() {
        initComponents();
        setLocation(400,100);
        setSize(649, 541);
        mostrartabla();
        aviso.setVisible(false);
        
        
        
        atras.setVisible(true);
        atras.setContentAreaFilled(false);
        atras.setBorderPainted (false);
        
       menub.setVisible(true);
        menub.setContentAreaFilled(false);
        menub.setBorderPainted (false);
        
        salir.setVisible(true);
        salir.setContentAreaFilled(false);
        salir.setBorderPainted (false);
        
        transparenciaButton();
    }
    
    public void transparenciaButton (){
         atras.setOpaque(false);
         menub.setOpaque(false);
         salir.setOpaque(false);
    }
    
    void mostrartabla(){
        DefaultTableModel modelo= new DefaultTableModel();
        modelo.addColumn("Tarea");
        modelo.addColumn("Fecha");
        modelo.addColumn("Verificacion");
        tabla.setModel(modelo);
        String sql= "Select * from tareas";
        Statement st;
        try{
            String datos[] =new String [3];
            st =cn.createStatement();
            ResultSet rs= st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(2);
                datos[1]=rs.getString(3);
                datos[2]=rs.getString(4);
                modelo.addRow(datos);
            }
            tabla.setModel(modelo);
            
        }catch (SQLException ex){
            Logger.getLogger(Promedio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        editbutton = new javax.swing.JButton();
        showbutton1 = new javax.swing.JButton();
        aviso = new javax.swing.JTextField();
        atras = new javax.swing.JButton();
        menub = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setBackground(new java.awt.Color(204, 204, 255));
        tabla.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tarea", "Fecha", "Verificacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setPreferredWidth(10);
            tabla.getColumnModel().getColumn(1).setPreferredWidth(5);
            tabla.getColumnModel().getColumn(2).setPreferredWidth(5);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 480, 300));

        editbutton.setBackground(new java.awt.Color(204, 204, 204));
        editbutton.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        editbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pluma.png"))); // NOI18N
        editbutton.setText("EDITAR");
        editbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(editbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 120, 50));

        showbutton1.setBackground(new java.awt.Color(204, 204, 204));
        showbutton1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        showbutton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ojo.png"))); // NOI18N
        showbutton1.setText("OCULTAR RECORDATORIOS");
        showbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showbutton1ActionPerformed(evt);
            }
        });
        getContentPane().add(showbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 250, 50));
        getContentPane().add(aviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras2.png"))); // NOI18N
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        getContentPane().add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 60, 30));

        menub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/init.png"))); // NOI18N
        menub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubActionPerformed(evt);
            }
        });
        getContentPane().add(menub, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, -1, -1));

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 30, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BASICO MEDIDAS.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 650, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbuttonActionPerformed
        try {
            tabla.setVisible(false);
            DefaultTableModel tm = (DefaultTableModel) tabla.getModel();
            String dato = String.valueOf(tm.getValueAt(tabla.getSelectedRow(), 0));
            String dat;
            ResultSet rs;
            Statement st;
            String sql = ("SELECT CodTarea from tareas WHERE Descripcion='" + dato + "'");
            try {
                st = cn.createStatement();
                rs = st.executeQuery(sql);
                while (rs.next()) {
                    dat = rs.getString(1);
                    aviso.setText("" + dat);
                }

            } catch (SQLException ex) {
                Logger.getLogger(ANota.class.getName()).log(Level.SEVERE, null, ex);
            }
            new ERecor().setVisible(true);
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Seleccione una tarea para editar");
            dispose();
            new tareas().setVisible(true);
        }
        

    }//GEN-LAST:event_editbuttonActionPerformed

    private void showbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showbutton1ActionPerformed
       dispose();
       new NotasR().setVisible(true);
    }//GEN-LAST:event_showbutton1ActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        new NotasR().setVisible(true);
        dispose();
    }//GEN-LAST:event_atrasActionPerformed

    private void menubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubActionPerformed
        new Ventana().setVisible(true);
        //new tareas().setVisible(false);
        //new ERecor().setVisible(false);
        this.setVisible(false);
    }//GEN-LAST:event_menubActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tareas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    public static javax.swing.JTextField aviso;
    private javax.swing.JButton editbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton menub;
    private javax.swing.JButton salir;
    private javax.swing.JButton showbutton1;
    public static javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
